"""Typed boundary to the small JavaScript host. Only JSON and strings cross it."""

from collections.abc import Awaitable, Callable
from typing import Protocol


class Proxy(Protocol):
    def destroy(self) -> None: ...


class Host(Protocol):
    def render(self, markup: str, focus: str) -> None: ...
    def bind(self, callback: Proxy) -> None: ...
    def snapshot(self) -> Awaitable[str]: ...
    def transact(self, callback: Proxy) -> Awaitable[str]: ...
    def download(self, contents: str, filename: str) -> None: ...
    def persist(self) -> Awaitable[bool]: ...
    def environment(self) -> str: ...
    def date(self, timestamp: int) -> str: ...
    def scroll(self) -> None: ...
    def update(self) -> Awaitable[None]: ...


class ProxyFactory(Protocol):
    def __call__(self, callback: Callable[..., object]) -> Proxy: ...
