/** Rebuild offline catalog from its checked-in selection and measured counts. No network. */
import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { Chess } from 'chess.js';
import { classifyPgn } from './catalog-classifier.mjs';

const selection = JSON.parse(
  await readFile(new URL('./catalog-selection.json', import.meta.url), 'utf8'),
);
const countsUrl = new URL('./catalog-counts.json', import.meta.url);
const paths = process.argv.slice(2);
let reference;
if (paths.length) {
  const counts = Object.fromEntries(selection.map((line) => [line.id, 0]));
  reference = {
    source: process.env.CATALOG_SOURCE || 'User-supplied PGN sample',
    description:
      process.env.CATALOG_DESCRIPTION ||
      'Exact move-order counts from supplied PGN games; not a population estimate.',
    date: process.env.CATALOG_DATE || new Date().toISOString().slice(0, 10),
    method: 'longest-exact-mainline-prefix',
    totalGames: 0,
    classifiedGames: 0,
    skippedGames: 0,
    unclassifiedGames: 0,
    files: [],
    counts,
  };
  for (const path of paths) {
    const bytes = await readFile(path);
    const result = classifyPgn(bytes.toString('utf8'), selection);
    for (const key of ['totalGames', 'classifiedGames', 'skippedGames', 'unclassifiedGames'])
      reference[key] += result[key];
    for (const [id, count] of Object.entries(result.counts)) counts[id] += count;
    reference.files.push({
      filename: path.split('/').at(-1),
      sha256: createHash('sha256').update(bytes).digest('hex'),
      games: result.totalGames,
    });
  }
  await writeFile(countsUrl, JSON.stringify(reference, null, 2) + '\n');
} else reference = JSON.parse(await readFile(countsUrl, 'utf8'));

const lines = selection.map((line) => {
  const board = new Chess();
  board.loadPgn(line.pgn);
  const moves = board
    .history({ verbose: true })
    .map((move) => move.from + move.to + (move.promotion || ''));
  const popularity = reference.counts[line.id];
  if (!Number.isSafeInteger(popularity) || popularity < 0)
    throw new Error(`Invalid count: ${line.id}`);
  return {
    id: line.id,
    familyId: line.familyId,
    family: line.family,
    name: line.name,
    eco: line.eco,
    moves,
    popularity,
    description: `Learn the ${moves.length}-ply sequence to this named position.`,
  };
});
const metadata = {
  version:
    '1-' +
    createHash('sha256')
      .update(JSON.stringify({ selection, reference }))
      .digest('hex')
      .slice(0, 12),
  date: reference.date,
  source: reference.source,
  description: reference.description,
  sourceCommit: '4b8622759e7ae6f93f011cc6c83a3823401ab45e',
  sourceUrl:
    'https://github.com/lichess-org/chess-openings/tree/4b8622759e7ae6f93f011cc6c83a3823401ab45e',
  popularityMethod: reference.method,
  totalGames: reference.totalGames,
  classifiedGames: reference.classifiedGames,
  unclassifiedGames: reference.unclassifiedGames,
  skippedGames: reference.skippedGames,
  lineCount: lines.length,
  familyCount: new Set(lines.map((line) => line.familyId)).size,
};
await writeFile(
  new URL('../src/data/catalog.ts', import.meta.url),
  '// Generated by node scripts/catalog-build.mjs. Edit scripts/catalog-selection.json instead.\n' +
    "import type { OpeningLine } from '../types';\n\n" +
    `export const catalogMetadata = ${JSON.stringify(metadata, null, 2)} as const;\n\n` +
    `export const openings: OpeningLine[] = ${JSON.stringify(lines, null, 2)};\n`,
);
console.log(
  `Generated ${lines.length} drills; classified ${reference.classifiedGames}/${reference.totalGames} source games.`,
);
